# Generated by Django 4.2 on 2023-06-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_user_managers_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cor',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='apply',
            name='cov_let',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='apply',
            name='school_id',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.CharField(max_length=24),
        ),
    ]
